name: NestJS CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code từ GitHub
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js version 18
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Cài dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build project NestJS
      - name: Build application
        run: npm run build

      # 5️⃣ Chạy e2e test (có thể bỏ nếu bạn muốn cực kỳ đơn giản)
      - name: Run e2e tests
        run: npm run test:e2e
